// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sms.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sms.proto

It has these top-level messages:
	SendSmsRequest
	SendSmsRespose
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 发送短信请求参数, 具体请参考链接
// https://help.aliyun.com/document_detail/55284.html?spm=5176.doc56189.6.552.9Bi058
type SendSmsRequest struct {
	PhoneNumbers    string `protobuf:"bytes,1,opt,name=PhoneNumbers" json:"PhoneNumbers,omitempty"`
	SignName        string `protobuf:"bytes,2,opt,name=SignName" json:"SignName,omitempty"`
	TemplateCode    string `protobuf:"bytes,3,opt,name=TemplateCode" json:"TemplateCode,omitempty"`
	TemplateParam   string `protobuf:"bytes,4,opt,name=TemplateParam" json:"TemplateParam,omitempty"`
	OutId           string `protobuf:"bytes,5,opt,name=OutId" json:"OutId,omitempty"`
	SmsUpExtendCode string `protobuf:"bytes,6,opt,name=smsUpExtendCode" json:"smsUpExtendCode,omitempty"`
}

func (m *SendSmsRequest) Reset()                    { *m = SendSmsRequest{} }
func (m *SendSmsRequest) String() string            { return proto.CompactTextString(m) }
func (*SendSmsRequest) ProtoMessage()               {}
func (*SendSmsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendSmsRequest) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *SendSmsRequest) GetSignName() string {
	if m != nil {
		return m.SignName
	}
	return ""
}

func (m *SendSmsRequest) GetTemplateCode() string {
	if m != nil {
		return m.TemplateCode
	}
	return ""
}

func (m *SendSmsRequest) GetTemplateParam() string {
	if m != nil {
		return m.TemplateParam
	}
	return ""
}

func (m *SendSmsRequest) GetOutId() string {
	if m != nil {
		return m.OutId
	}
	return ""
}

func (m *SendSmsRequest) GetSmsUpExtendCode() string {
	if m != nil {
		return m.SmsUpExtendCode
	}
	return ""
}

// 发送短信响应参数, 具体请参考链接
// https://help.aliyun.com/document_detail/55284.html?spm=5176.doc56189.6.552.9Bi058
type SendSmsRespose struct {
	RequestId string `protobuf:"bytes,1,opt,name=RequestId" json:"RequestId,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=Code" json:"Code,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
	BizId     string `protobuf:"bytes,4,opt,name=BizId" json:"BizId,omitempty"`
}

func (m *SendSmsRespose) Reset()                    { *m = SendSmsRespose{} }
func (m *SendSmsRespose) String() string            { return proto.CompactTextString(m) }
func (*SendSmsRespose) ProtoMessage()               {}
func (*SendSmsRespose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendSmsRespose) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SendSmsRespose) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SendSmsRespose) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendSmsRespose) GetBizId() string {
	if m != nil {
		return m.BizId
	}
	return ""
}

func init() {
	proto.RegisterType((*SendSmsRequest)(nil), "pb.SendSmsRequest")
	proto.RegisterType((*SendSmsRespose)(nil), "pb.SendSmsRespose")
}

func init() { proto.RegisterFile("sms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4b, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xd2, 0x16, 0x32, 0xe2, 0x21, 0x8d, 0x58, 0x58, 0x88, 0x05, 0x8a, 0x58, 0x74,
	0xc5, 0x86, 0x1b, 0x80, 0x58, 0x64, 0x41, 0xa9, 0x1a, 0x38, 0x80, 0x23, 0x8f, 0x4a, 0x25, 0xfc,
	0xc0, 0xe3, 0x48, 0x88, 0xa3, 0x72, 0x1a, 0xd4, 0x71, 0x02, 0x4d, 0x77, 0xf9, 0xbf, 0x3f, 0x63,
	0xcf, 0x67, 0x28, 0xd9, 0xf2, 0x5d, 0x88, 0x3e, 0x79, 0x9c, 0x84, 0xb6, 0xfa, 0x29, 0xe0, 0xbc,
	0x21, 0x67, 0x1a, 0xcb, 0x6b, 0xfa, 0xec, 0x88, 0x13, 0x56, 0x70, 0xba, 0x7a, 0xf7, 0x8e, 0x96,
	0x9d, 0x6d, 0x29, 0xb2, 0x2a, 0x6e, 0x8a, 0x45, 0xb9, 0x1e, 0x31, 0xbc, 0x82, 0x93, 0x66, 0xbb,
	0x71, 0x4b, 0x6d, 0x49, 0x4d, 0xa4, 0xff, 0xcb, 0xbb, 0xf9, 0x57, 0xb2, 0xe1, 0x43, 0x27, 0x7a,
	0xf4, 0x86, 0xd4, 0x51, 0x9e, 0xdf, 0x67, 0x78, 0x0b, 0x67, 0x43, 0x5e, 0xe9, 0xa8, 0xad, 0x9a,
	0xca, 0x4f, 0x63, 0x88, 0x97, 0x30, 0x7b, 0xe9, 0x52, 0x6d, 0xd4, 0x4c, 0xda, 0x1c, 0x70, 0x01,
	0x17, 0x6c, 0xf9, 0x2d, 0x3c, 0x7d, 0x25, 0x72, 0x46, 0xae, 0x98, 0x4b, 0x7f, 0x88, 0xab, 0xb8,
	0xe7, 0xc6, 0xc1, 0x33, 0xe1, 0x35, 0x94, 0xbd, 0x66, 0x6d, 0x7a, 0xb1, 0x7f, 0x80, 0x08, 0x53,
	0x39, 0x2e, 0x1b, 0xc9, 0x37, 0x2a, 0x38, 0x7e, 0x26, 0x66, 0xbd, 0x19, 0x44, 0x86, 0xb8, 0xdb,
	0xee, 0x61, 0xfb, 0x5d, 0x9b, 0x7e, 0xf7, 0x1c, 0xda, 0xb9, 0xbc, 0xed, 0xfd, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7c, 0x82, 0x3b, 0xc1, 0x68, 0x01, 0x00, 0x00,
}
